### ISSUE TITLE
What is the difference between dstdgcn.py and dstdgcn_fast.py in the model

### ISSUE THREAD

**Issue by bwshen93** [Jaakk0F/DSTD-GCN#1]
Thank you for your contribution and sharing. What is the difference between dstdgcn.py and dstdgcn_fast.py in the model? Which model should be selected for training and testing

**Comment by csjjfu** [comment]
Thanks for your interest. These two files both implement our proposed DSTD-GCN; they are equivalent. The main difference is 
 the implementation of feature aggregation: `dstdgcn.py` utilizes the Einstein summation operation, while `dstdgcn_fast.py` adopts tensor permutation and matrix multiplication. We find the latter one runs faster in inference. In our experiments, we utilize `dstdgcn.py` for qualitative and quantitative evaluation, and `dstdgcn_fast.py` for inference time evaluation.

**Comment by bwshen93** [comment]
Thank you for your answer. There is one more question. The dataset I am processing has 17 key points for the human body, and I am currently unsure of what the skeletal structure of the human body will be based on these 17 key points? May I ask if you can provide some references? If there are 17 joints, do we need to change the joints in the Graph

**Comment by csjjfu** [comment]
Do you mean you need clarification on the spatial connections between the 17 key points? If so, I suggest you visualize their movement by different colors and try to figure out each key point's semantic information (elbow, foot, head, etc.). With the semantic information, you can clarify the spatial connections between joints. As a reference, [a blog in Chinese](https://fesian.blog.csdn.net/article/details/108242717) shows the joint's semantic information in different datasets.
After this step, I suggest you modify the initialized constrained spatial correlation. Fig. 9 (a) and (b) in our paper provide a visual example. In implementation, you should modify `model/layers/graph.py` to clarify joint connections.

**Comment by bwshen93** [comment]
Okay, I'll give it a try
Thank you very much for your reply
